# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker account connection'
    repository: 'doughertyaaron/web-app-devops-project'
    command: 'buildAndPush'
    Dockerfile: '**/dockerfile'
    tags: 'version1'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'AKS DevOps Project Cluster'
    manifests: 'application-manifest.yaml'